### ISSUE TITLE
Расчет примитивной таблицы

### ISSUE THREAD

**Issue by nergal-perm** [nergal-perm/java-decita#1]
Нужно организовать расчет примитивной таблицы из одного Правила, одного Условия и одного Исхода. Что-то вроде этого:

| Fragment / Outcome | Rule 1 |
|--------|--------|
| const_boolean::true | true |
| outcome | true | 

Для этого понадобится организовать поиск Фрагментов, операцию сравнения в простом Условии и запись результата расчета таблицы.

**Comment by 0pdd** [comment]
@nergal-perm the puzzle [#4](https://github.com/nergal-perm/java-decita/issues/4) is still not solved.

**Comment by 0pdd** [comment]
@nergal-perm 4 puzzles [#4](https://github.com/nergal-perm/java-decita/issues/4), [#6](https://github.com/nergal-perm/java-decita/issues/6), [#7](https://github.com/nergal-perm/java-decita/issues/7), [#8](https://github.com/nergal-perm/java-decita/issues/8) are still not solved.

**Comment by 0pdd** [comment]
@nergal-perm 3 puzzles [#11](https://github.com/nergal-perm/java-decita/issues/11), [#4](https://github.com/nergal-perm/java-decita/issues/4), [#8](https://github.com/nergal-perm/java-decita/issues/8) are still not solved; solved: [#6](https://github.com/nergal-perm/java-decita/issues/6), [#7](https://github.com/nergal-perm/java-decita/issues/7).

**Comment by 0pdd** [comment]
@nergal-perm 4 puzzles [#11](https://github.com/nergal-perm/java-decita/issues/11), [#13](https://github.com/nergal-perm/java-decita/issues/13), [#4](https://github.com/nergal-perm/java-decita/issues/4), [#8](https://github.com/nergal-perm/java-decita/issues/8) are still not solved; solved: [#6](https://github.com/nergal-perm/java-decita/issues/6), [#7](https://github.com/nergal-perm/java-decita/issues/7).

**Comment by 0pdd** [comment]
@nergal-perm 3 puzzles [#13](https://github.com/nergal-perm/java-decita/issues/13), [#4](https://github.com/nergal-perm/java-decita/issues/4), [#8](https://github.com/nergal-perm/java-decita/issues/8) are still not solved; solved: [#11](https://github.com/nergal-perm/java-decita/issues/11), [#6](https://github.com/nergal-perm/java-decita/issues/6), [#7](https://github.com/nergal-perm/java-decita/issues/7).

**Comment by 0pdd** [comment]
@nergal-perm 4 puzzles [#13](https://github.com/nergal-perm/java-decita/issues/13), [#15](https://github.com/nergal-perm/java-decita/issues/15), [#16](https://github.com/nergal-perm/java-decita/issues/16), [#4](https://github.com/nergal-perm/java-decita/issues/4) are still not solved; solved: [#11](https://github.com/nergal-perm/java-decita/issues/11), [#6](https://github.com/nergal-perm/java-decita/issues/6), [#7](https://github.com/nergal-perm/java-decita/issues/7), [#8](https://github.com/nergal-perm/java-decita/issues/8).

**Comment by 0pdd** [comment]
@nergal-perm 3 puzzles [#13](https://github.com/nergal-perm/java-decita/issues/13), [#16](https://github.com/nergal-perm/java-decita/issues/16), [#4](https://github.com/nergal-perm/java-decita/issues/4) are still not solved; solved: [#11](https://github.com/nergal-perm/java-decita/issues/11), [#15](https://github.com/nergal-perm/java-decita/issues/15), [#6](https://github.com/nergal-perm/java-decita/issues/6), [#7](https://github.com/nergal-perm/java-decita/issues/7), [#8](https://github.com/nergal-perm/java-decita/issues/8).

**Comment by 0pdd** [comment]
@nergal-perm 4 puzzles [#13](https://github.com/nergal-perm/java-decita/issues/13), [#16](https://github.com/nergal-perm/java-decita/issues/16), [#19](https://github.com/nergal-perm/java-decita/issues/19), [#4](https://github.com/nergal-perm/java-decita/issues/4) are still not solved; solved: [#11](https://github.com/nergal-perm/java-decita/issues/11), [#15](https://github.com/nergal-perm/java-decita/issues/15), [#6](https://github.com/nergal-perm/java-decita/issues/6), [#7](https://github.com/nergal-perm/java-decita/issues/7), [#8](https://github.com/nergal-perm/java-decita/issues/8).

**Comment by 0pdd** [comment]
@nergal-perm 3 puzzles [#13](https://github.com/nergal-perm/java-decita/issues/13), [#16](https://github.com/nergal-perm/java-decita/issues/16), [#4](https://github.com/nergal-perm/java-decita/issues/4) are still not solved; solved: [#11](https://github.com/nergal-perm/java-decita/issues/11), [#15](https://github.com/nergal-perm/java-decita/issues/15), [#19](https://github.com/nergal-perm/java-decita/issues/19), [#6](https://github.com/nergal-perm/java-decita/issues/6), [#7](https://github.com/nergal-perm/java-decita/issues/7), [#8](https://github.com/nergal-perm/java-decita/issues/8).

**Comment by 0pdd** [comment]
@nergal-perm 2 puzzles [#13](https://github.com/nergal-perm/java-decita/issues/13), [#4](https://github.com/nergal-perm/java-decita/issues/4) are still not solved; solved: [#11](https://github.com/nergal-perm/java-decita/issues/11), [#15](https://github.com/nergal-perm/java-decita/issues/15), [#16](https://github.com/nergal-perm/java-decita/issues/16), [#19](https://github.com/nergal-perm/java-decita/issues/19), [#6](https://github.com/nergal-perm/java-decita/issues/6), [#7](https://github.com/nergal-perm/java-decita/issues/7), [#8](https://github.com/nergal-perm/java-decita/issues/8).

**Comment by 0pdd** [comment]
@nergal-perm 2 puzzles [#22](https://github.com/nergal-perm/java-decita/issues/22), [#4](https://github.com/nergal-perm/java-decita/issues/4) are still not solved; solved: [#11](https://github.com/nergal-perm/java-decita/issues/11), [#13](https://github.com/nergal-perm/java-decita/issues/13), [#15](https://github.com/nergal-perm/java-decita/issues/15), [#16](https://github.com/nergal-perm/java-decita/issues/16), [#19](https://github.com/nergal-perm/java-decita/issues/19), [#6](https://github.com/nergal-perm/java-decita/issues/6), [#7](https://github.com/nergal-perm/java-decita/issues/7), [#8](https://github.com/nergal-perm/java-decita/issues/8).

**Comment by 0pdd** [comment]
@nergal-perm 2 puzzles [#25](https://github.com/nergal-perm/java-decita/issues/25), [#4](https://github.com/nergal-perm/java-decita/issues/4) are still not solved; solved: [#11](https://github.com/nergal-perm/java-decita/issues/11), [#13](https://github.com/nergal-perm/java-decita/issues/13), [#15](https://github.com/nergal-perm/java-decita/issues/15), [#16](https://github.com/nergal-perm/java-decita/issues/16), [#19](https://github.com/nergal-perm/java-decita/issues/19), [#22](https://github.com/nergal-perm/java-decita/issues/22), [#6](https://github.com/nergal-perm/java-decita/issues/6), [#7](https://github.com/nergal-perm/java-decita/issues/7), [#8](https://github.com/nergal-perm/java-decita/issues/8).

**Comment by 0pdd** [comment]
@nergal-perm 2 puzzles [#28](https://github.com/nergal-perm/java-decita/issues/28), [#4](https://github.com/nergal-perm/java-decita/issues/4) are still not solved; solved: [#11](https://github.com/nergal-perm/java-decita/issues/11), [#13](https://github.com/nergal-perm/java-decita/issues/13), [#15](https://github.com/nergal-perm/java-decita/issues/15), [#16](https://github.com/nergal-perm/java-decita/issues/16), [#19](https://github.com/nergal-perm/java-decita/issues/19), [#22](https://github.com/nergal-perm/java-decita/issues/22), [#25](https://github.com/nergal-perm/java-decita/issues/25), [#6](https://github.com/nergal-perm/java-decita/issues/6), [#7](https://github.com/nergal-perm/java-decita/issues/7), [#8](https://github.com/nergal-perm/java-decita/issues/8).

**Comment by 0pdd** [comment]
@nergal-perm all 12 puzzles are solved here: [#11](https://github.com/nergal-perm/java-decita/issues/11), [#13](https://github.com/nergal-perm/java-decita/issues/13), [#15](https://github.com/nergal-perm/java-decita/issues/15), [#16](https://github.com/nergal-perm/java-decita/issues/16), [#19](https://github.com/nergal-perm/java-decita/issues/19), [#22](https://github.com/nergal-perm/java-decita/issues/22), [#25](https://github.com/nergal-perm/java-decita/issues/25), [#28](https://github.com/nergal-perm/java-decita/issues/28), [#4](https://github.com/nergal-perm/java-decita/issues/4), [#6](https://github.com/nergal-perm/java-decita/issues/6), [#7](https://github.com/nergal-perm/java-decita/issues/7), [#8](https://github.com/nergal-perm/java-decita/issues/8).
