### ISSUE TITLE
Implement the simplest command description

### ISSUE THREAD

**Issue by nergal-perm** [nergal-perm/java-decita#103]
It can be a command that sets a singe abstract context's field to a predefined constant value, described like that:
```yaml
operations: "table::name -> Tic-Tac-Toe"
```

**Comment by 0pdd** [comment]
@nergal-perm 3 puzzles [#104](https://github.com/nergal-perm/java-decita/issues/104), [#105](https://github.com/nergal-perm/java-decita/issues/105), [#106](https://github.com/nergal-perm/java-decita/issues/106) are still not solved.

**Comment by 0pdd** [comment]
@nergal-perm 2 puzzles [#105](https://github.com/nergal-perm/java-decita/issues/105), [#106](https://github.com/nergal-perm/java-decita/issues/106) are still not solved; solved: [#104](https://github.com/nergal-perm/java-decita/issues/104).

**Comment by 0pdd** [comment]
@nergal-perm the puzzle [#106](https://github.com/nergal-perm/java-decita/issues/106) is still not solved; solved: [#104](https://github.com/nergal-perm/java-decita/issues/104), [#105](https://github.com/nergal-perm/java-decita/issues/105).

**Comment by 0pdd** [comment]
@nergal-perm all 3 puzzles are solved here: [#104](https://github.com/nergal-perm/java-decita/issues/104), [#105](https://github.com/nergal-perm/java-decita/issues/105), [#106](https://github.com/nergal-perm/java-decita/issues/106).
