### ISSUE TITLE
Create separate classes for Tables, Commands and State Locators

### ISSUE THREAD

**Issue by nergal-perm** [nergal-perm/java-decita#115]

**Comment by 0pdd** [comment]
@nergal-perm the puzzle [#116](https://github.com/nergal-perm/java-decita/issues/116) is still not solved.

**Comment by 0pdd** [comment]
@nergal-perm the only puzzle [#116](https://github.com/nergal-perm/java-decita/issues/116) is solved here.

**Comment by nergal-perm** [comment]
Commands could now live as an object out of Locators hierarchy
