### ISSUE TITLE
Implement request-based ComputationContext instances

### ISSUE THREAD

**Issue by nergal-perm** [nergal-perm/java-decita#122]

**Comment by 0pdd** [comment]
@nergal-perm 3 puzzles [#123](https://github.com/nergal-perm/java-decita/issues/123), [#124](https://github.com/nergal-perm/java-decita/issues/124), [#125](https://github.com/nergal-perm/java-decita/issues/125) are still not solved.

**Comment by 0pdd** [comment]
@nergal-perm 5 puzzles [#123](https://github.com/nergal-perm/java-decita/issues/123), [#124](https://github.com/nergal-perm/java-decita/issues/124), [#125](https://github.com/nergal-perm/java-decita/issues/125), [#126](https://github.com/nergal-perm/java-decita/issues/126), [#127](https://github.com/nergal-perm/java-decita/issues/127) are still not solved.

**Comment by 0pdd** [comment]
@nergal-perm 4 puzzles [#123](https://github.com/nergal-perm/java-decita/issues/123), [#124](https://github.com/nergal-perm/java-decita/issues/124), [#125](https://github.com/nergal-perm/java-decita/issues/125), [#127](https://github.com/nergal-perm/java-decita/issues/127) are still not solved; solved: [#126](https://github.com/nergal-perm/java-decita/issues/126).

**Comment by 0pdd** [comment]
@nergal-perm 5 puzzles [#123](https://github.com/nergal-perm/java-decita/issues/123), [#124](https://github.com/nergal-perm/java-decita/issues/124), [#125](https://github.com/nergal-perm/java-decita/issues/125), [#127](https://github.com/nergal-perm/java-decita/issues/127), [#128](https://github.com/nergal-perm/java-decita/issues/128) are still not solved; solved: [#126](https://github.com/nergal-perm/java-decita/issues/126).

**Comment by 0pdd** [comment]
@nergal-perm 4 puzzles [#123](https://github.com/nergal-perm/java-decita/issues/123), [#124](https://github.com/nergal-perm/java-decita/issues/124), [#125](https://github.com/nergal-perm/java-decita/issues/125), [#127](https://github.com/nergal-perm/java-decita/issues/127) are still not solved; solved: [#126](https://github.com/nergal-perm/java-decita/issues/126), [#128](https://github.com/nergal-perm/java-decita/issues/128).

**Comment by 0pdd** [comment]
@nergal-perm 5 puzzles [#123](https://github.com/nergal-perm/java-decita/issues/123), [#124](https://github.com/nergal-perm/java-decita/issues/124), [#125](https://github.com/nergal-perm/java-decita/issues/125), [#127](https://github.com/nergal-perm/java-decita/issues/127), [#129](https://github.com/nergal-perm/java-decita/issues/129) are still not solved; solved: [#126](https://github.com/nergal-perm/java-decita/issues/126), [#128](https://github.com/nergal-perm/java-decita/issues/128).

**Comment by 0pdd** [comment]
@nergal-perm 4 puzzles [#123](https://github.com/nergal-perm/java-decita/issues/123), [#124](https://github.com/nergal-perm/java-decita/issues/124), [#127](https://github.com/nergal-perm/java-decita/issues/127), [#129](https://github.com/nergal-perm/java-decita/issues/129) are still not solved; solved: [#125](https://github.com/nergal-perm/java-decita/issues/125), [#126](https://github.com/nergal-perm/java-decita/issues/126), [#128](https://github.com/nergal-perm/java-decita/issues/128).

**Comment by 0pdd** [comment]
@nergal-perm 5 puzzles [#123](https://github.com/nergal-perm/java-decita/issues/123), [#124](https://github.com/nergal-perm/java-decita/issues/124), [#127](https://github.com/nergal-perm/java-decita/issues/127), [#129](https://github.com/nergal-perm/java-decita/issues/129), [#130](https://github.com/nergal-perm/java-decita/issues/130) are still not solved; solved: [#125](https://github.com/nergal-perm/java-decita/issues/125), [#126](https://github.com/nergal-perm/java-decita/issues/126), [#128](https://github.com/nergal-perm/java-decita/issues/128).

**Comment by 0pdd** [comment]
@nergal-perm all 8 puzzles are solved here: [#123](https://github.com/nergal-perm/java-decita/issues/123), [#124](https://github.com/nergal-perm/java-decita/issues/124), [#125](https://github.com/nergal-perm/java-decita/issues/125), [#126](https://github.com/nergal-perm/java-decita/issues/126), [#127](https://github.com/nergal-perm/java-decita/issues/127), [#128](https://github.com/nergal-perm/java-decita/issues/128), [#129](https://github.com/nergal-perm/java-decita/issues/129), [#130](https://github.com/nergal-perm/java-decita/issues/130).
