### ISSUE TITLE
Refactor the Locator registration process, probably it can be done with fluent API or something...

### ISSUE THREAD

**Issue by 0pdd** [nergal-perm/java-decita#13]
The puzzle `4-d4ffc0ee` from #4 has to be resolved: 

https://github.com/nergal-perm/java-decita/blob/6b9199f9d8026ec00add73e6a04c730efd6ee628/src/main/java/ru/ewc/decita/ComputationContext.java#L71-L72

The puzzle was created by Евгений Терехов on 01-Jan-24. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
The puzzle `4-d4ffc0ee` has disappeared from the source code, that's why I closed this issue.

**Comment by nergal-perm** [comment]
Actually, it should be done later. Right now it's not required, I can move on without this refactoring.
