### ISSUE TITLE
Turn SourceLines into a simple ordered list of typed lines

### ISSUE THREAD

**Issue by nergal-perm** [nergal-perm/java-decita#153]
The main idea is to have just an ordered list of lines, each having it's type defined. That list of lines can be used differently by different interpreters.

**Comment by 0pdd** [comment]
@nergal-perm the puzzle [#156](https://github.com/nergal-perm/java-decita/issues/156) is still not solved.

**Comment by 0pdd** [comment]
@nergal-perm the only puzzle [#156](https://github.com/nergal-perm/java-decita/issues/156) is solved here.
