### ISSUE TITLE
Make Rule internals use SourceLines, store only String pairs

### ISSUE THREAD

**Issue by nergal-perm** [nergal-perm/java-decita#154]

**Comment by 0pdd** [comment]
@nergal-perm the puzzle [#155](https://github.com/nergal-perm/java-decita/issues/155) is still not solved.

**Comment by 0pdd** [comment]
@nergal-perm the only puzzle [#155](https://github.com/nergal-perm/java-decita/issues/155) is solved here.

**Comment by 0pdd** [comment]
@nergal-perm the puzzle [#157](https://github.com/nergal-perm/java-decita/issues/157) is still not solved; solved: [#155](https://github.com/nergal-perm/java-decita/issues/155).

**Comment by 0pdd** [comment]
@nergal-perm the puzzle [#158](https://github.com/nergal-perm/java-decita/issues/158) is still not solved; solved: [#155](https://github.com/nergal-perm/java-decita/issues/155), [#157](https://github.com/nergal-perm/java-decita/issues/157).

**Comment by 0pdd** [comment]
@nergal-perm all 3 puzzles are solved here: [#155](https://github.com/nergal-perm/java-decita/issues/155), [#157](https://github.com/nergal-perm/java-decita/issues/157), [#158](https://github.com/nergal-perm/java-decita/issues/158).
