### ISSUE TITLE
Make Coordinates mutable in order to get rid of StateFragments

### ISSUE THREAD

**Issue by 0pdd** [nergal-perm/java-decita#19]
The puzzle `16-a8ef584e` from #16 has to be resolved: 

https://github.com/nergal-perm/java-decita/blob/8f6b1d29254c6e06356cdd66019e0c3d16d1a2bf/src/main/java/ru/ewc/decita/Rule.java#L33-L34

The puzzle was created by Евгений Терехов on 09-Jan-24. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by nergal-perm** [comment]
It is possible to use only Coordinates in a computation, it will be simpler because all the computation's components will be of the same type.

**Comment by 0pdd** [comment]
The puzzle `16-a8ef584e` has disappeared from the source code, that's why I closed this issue.
