### ISSUE TITLE
Present 0-Order Conditions as a Decision Table special case

### ISSUE THREAD

**Issue by nergal-perm** [nergal-perm/java-decita#31]
0-Order or "Business Conditions" are those that use real business data to compute themselves. Those Conditions can use any comparison operation they like, they all have some business semantics, and they all are useless by themselves. Their purpose is to serve as building blocks for Decision tables. 

My first idea was to describe those Conditions as a separate entity using a special format, but it seems unnecessary, because every Condition can be expressed in terms of Decision Tables and Coordinates.

The main challenge here is to make the comparison operation explicit, parse it from the input sources and use it inside Decision Table's cells. Probably it will require some kind of DSL to express all the possible/wanted comparisons.

**Comment by 0pdd** [comment]
@nergal-perm 3 puzzles [#32](https://github.com/nergal-perm/java-decita/issues/32), [#33](https://github.com/nergal-perm/java-decita/issues/33), [#34](https://github.com/nergal-perm/java-decita/issues/34) are still not solved.

**Comment by 0pdd** [comment]
@nergal-perm 4 puzzles [#32](https://github.com/nergal-perm/java-decita/issues/32), [#33](https://github.com/nergal-perm/java-decita/issues/33), [#34](https://github.com/nergal-perm/java-decita/issues/34), [#36](https://github.com/nergal-perm/java-decita/issues/36) are still not solved.

**Comment by 0pdd** [comment]
@nergal-perm 3 puzzles [#32](https://github.com/nergal-perm/java-decita/issues/32), [#33](https://github.com/nergal-perm/java-decita/issues/33), [#34](https://github.com/nergal-perm/java-decita/issues/34) are still not solved; solved: [#36](https://github.com/nergal-perm/java-decita/issues/36).

**Comment by 0pdd** [comment]
@nergal-perm the puzzle [#34](https://github.com/nergal-perm/java-decita/issues/34) is still not solved; solved: [#32](https://github.com/nergal-perm/java-decita/issues/32), [#33](https://github.com/nergal-perm/java-decita/issues/33), [#36](https://github.com/nergal-perm/java-decita/issues/36).

**Comment by 0pdd** [comment]
@nergal-perm all 4 puzzles are solved here: [#32](https://github.com/nergal-perm/java-decita/issues/32), [#33](https://github.com/nergal-perm/java-decita/issues/33), [#34](https://github.com/nergal-perm/java-decita/issues/34), [#36](https://github.com/nergal-perm/java-decita/issues/36).

**Comment by nergal-perm** [comment]
It seems that all the work is done, and the engine is ready to accept valid DecisionTables. In order to construct them from CSV-files there's another task: #40
