### ISSUE TITLE
Implement CSV-file parser for feeding tables into the engine

### ISSUE THREAD

**Issue by nergal-perm** [nergal-perm/java-decita#40]
What is needed:

- The ability to recursively load all the tables found in a folder
- Filename should become the table Location
- Conditions are built as Coordinate from first column (right part), then the comparison and the Coordinate (left part) from the table cell
- Outcomes should be somehow separated from the Conditions part (by `---` for example)

**Comment by 0pdd** [comment]
@nergal-perm 3 puzzles [#41](https://github.com/nergal-perm/java-decita/issues/41), [#42](https://github.com/nergal-perm/java-decita/issues/42), [#43](https://github.com/nergal-perm/java-decita/issues/43) are still not solved.

**Comment by 0pdd** [comment]
@nergal-perm 3 puzzles [#42](https://github.com/nergal-perm/java-decita/issues/42), [#43](https://github.com/nergal-perm/java-decita/issues/43), [#45](https://github.com/nergal-perm/java-decita/issues/45) are still not solved; solved: [#41](https://github.com/nergal-perm/java-decita/issues/41).

**Comment by 0pdd** [comment]
@nergal-perm 2 puzzles [#42](https://github.com/nergal-perm/java-decita/issues/42), [#43](https://github.com/nergal-perm/java-decita/issues/43) are still not solved; solved: [#41](https://github.com/nergal-perm/java-decita/issues/41), [#45](https://github.com/nergal-perm/java-decita/issues/45).

**Comment by 0pdd** [comment]
@nergal-perm 3 puzzles [#42](https://github.com/nergal-perm/java-decita/issues/42), [#43](https://github.com/nergal-perm/java-decita/issues/43), [#51](https://github.com/nergal-perm/java-decita/issues/51) are still not solved; solved: [#41](https://github.com/nergal-perm/java-decita/issues/41), [#45](https://github.com/nergal-perm/java-decita/issues/45).

**Comment by 0pdd** [comment]
@nergal-perm 2 puzzles [#43](https://github.com/nergal-perm/java-decita/issues/43), [#51](https://github.com/nergal-perm/java-decita/issues/51) are still not solved; solved: [#41](https://github.com/nergal-perm/java-decita/issues/41), [#42](https://github.com/nergal-perm/java-decita/issues/42), [#45](https://github.com/nergal-perm/java-decita/issues/45).

**Comment by 0pdd** [comment]
@nergal-perm all 5 puzzles are solved here: [#41](https://github.com/nergal-perm/java-decita/issues/41), [#42](https://github.com/nergal-perm/java-decita/issues/42), [#43](https://github.com/nergal-perm/java-decita/issues/43), [#45](https://github.com/nergal-perm/java-decita/issues/45), [#51](https://github.com/nergal-perm/java-decita/issues/51).

**Comment by nergal-perm** [comment]
The first draft of a parser is ready, issue can be closed.
