### ISSUE TITLE
Implement TableSources class to handle the implicit locator names

### ISSUE THREAD

**Issue by 0pdd** [nergal-perm/java-decita#51]
The puzzle `42-c9a96a8e` from #42 has to be resolved: 

https://github.com/nergal-perm/java-decita/blob/bd6f600e967a7ff89ccab98db20cd5ffce832115/src/main/java/ru/ewc/decita/input/package-info.java#L37-L43

The puzzle was created by Евгений Терехов on 25-Jan-24. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by nergal-perm** [comment]
It looks like premature optimization, so, I'll close the issue for now. Probably we'll work on that in future, but really not now.

**Comment by 0pdd** [comment]
The puzzle `42-c9a96a8e` has disappeared from the source code, that's why I closed this issue.
