### ISSUE TITLE
Implement TableSources class to handle the implicit locator names. My idea is to allow short...

### ISSUE THREAD

**Issue by 0pdd** [nergal-perm/java-decita#54]
The puzzle `23-c9a96a8e` from #23 has to be resolved: 

https://github.com/nergal-perm/java-decita/blob/68c63c9495a5dc902d3f47e79177ee7f9f9214e5/src/main/java/ru/ewc/decita/input/package-info.java#L35-L41

The puzzle was created by Евгений Терехов on 27-Jan-24. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by nergal-perm** [comment]
For the first take on that issue I'll just get rid of required `constant::` part of the Coordinate's description.
