### ISSUE TITLE
Create a shell for manual testing

### ISSUE THREAD

**Issue by nergal-perm** [nergal-perm/java-decita#61]
Something like interactive shell, but hide the Java code (vars and methods) behind more humane interface :)

**Comment by 0pdd** [comment]
@nergal-perm 3 puzzles [#62](https://github.com/nergal-perm/java-decita/issues/62), [#63](https://github.com/nergal-perm/java-decita/issues/63), [#64](https://github.com/nergal-perm/java-decita/issues/64) are still not solved.

**Comment by 0pdd** [comment]
@nergal-perm 3 puzzles [#63](https://github.com/nergal-perm/java-decita/issues/63), [#64](https://github.com/nergal-perm/java-decita/issues/64), [#66](https://github.com/nergal-perm/java-decita/issues/66) are still not solved; solved: [#62](https://github.com/nergal-perm/java-decita/issues/62).

**Comment by 0pdd** [comment]
@nergal-perm 2 puzzles [#63](https://github.com/nergal-perm/java-decita/issues/63), [#64](https://github.com/nergal-perm/java-decita/issues/64) are still not solved; solved: [#62](https://github.com/nergal-perm/java-decita/issues/62), [#66](https://github.com/nergal-perm/java-decita/issues/66).

**Comment by 0pdd** [comment]
@nergal-perm the puzzle [#64](https://github.com/nergal-perm/java-decita/issues/64) is still not solved; solved: [#62](https://github.com/nergal-perm/java-decita/issues/62), [#63](https://github.com/nergal-perm/java-decita/issues/63), [#66](https://github.com/nergal-perm/java-decita/issues/66).

**Comment by 0pdd** [comment]
@nergal-perm all 4 puzzles are solved here: [#62](https://github.com/nergal-perm/java-decita/issues/62), [#63](https://github.com/nergal-perm/java-decita/issues/63), [#64](https://github.com/nergal-perm/java-decita/issues/64), [#66](https://github.com/nergal-perm/java-decita/issues/66).
