### ISSUE TITLE
Implement a Facade for all the Decita functions

### ISSUE THREAD

**Issue by nergal-perm** [nergal-perm/java-decita#96]
For now it's just the way to call `decisionFor` method with an one-time extension for the ComputationContext (i.e. extend context with request data just for this very request)

**Comment by 0pdd** [comment]
@nergal-perm the puzzle [#97](https://github.com/nergal-perm/java-decita/issues/97) is still not solved.

**Comment by 0pdd** [comment]
@nergal-perm the only puzzle [#97](https://github.com/nergal-perm/java-decita/issues/97) is solved here.
